### ISSUE TITLE
Is posible to compile under Linux?

### ISSUE THREAD

**Issue by Pollito001** [Solokiller/HL_Tools#56] opened 2019-03-29 14:36 UTC
I want to know if i can compile on Linux?

**Comment by SamVanheer** [comment] 2019-03-29 20:34
No it doesn't work under Linux. Hopefully when the Avalonia UI works on Linux i can make a new model viewer that works cross platform.

**Comment by SamVanheer** [comment] 2019-04-05 12:10
I've reworked the CMake code for wxWidgets to make cross platform development easier, but i will not be porting it. If anybody else wants to do that it should be easier now.

**Comment by ninjafootball07** [comment] 2019-05-17 04:27
Where do you recommend I begin? I am interested in porting to linux and mac.

**Comment by SamVanheer** [comment] 2019-05-17 13:31
Set up the CMake dependencies and generate the build files. When i last tried a Linux build it worked aside from OpenGL not rendering anything. I don't know what the situation is now though.

**Comment by Solokiller** [comment] 2020-03-13 11:30
Duplicate of #10, closing. (feature is still planned)

**Closed by Solokiller** 2020-03-13 11:30 UTC
